"use client";
import styled from "styled-components";
import Image from "next/image";
import { use } from "react";
export default function Trumpcopy() {
  return (
    <TrumpContainer>
      <Image
        src="/img/1_of_clubs.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/1_of_diamonds.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/1_of_hearts.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/1_of_spades.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      {/* 2 */}
      <Image
        src="/img/2_of_clubs.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/2_of_diamonds.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/2_of_hearts.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/2_of_spades.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />

      {/* 3 */}
      <Image
        src="/img/3_of_clubs.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/3_of_diamonds.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/3_of_hearts.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/3_of_spades.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      {/* 4 */}
      <Image
        src="/img/4_of_clubs.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/4_of_diamonds.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/4_of_hearts.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/4_of_spades.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      {/* 5 */}
      <Image
        src="/img/5_of_clubs.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/5_of_diamonds.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/5_of_hearts.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/5_of_spades.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      {/* 6 */}
      <Image
        src="/img/6_of_clubs.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/6_of_diamonds.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/6_of_hearts.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/6_of_spades.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      {/* 7 */}
      <Image
        src="/img/7_of_clubs.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/7_of_diamonds.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/7_of_hearts.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/7_of_spades.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      {/* 8 */}
      <Image
        src="/img/8_of_clubs.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/8_of_diamonds.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/8_of_hearts.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/8_of_spades.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      {/* 9 */}
      <Image
        src="/img/9_of_clubs.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/9_of_diamonds.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/9_of_hearts.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/9_of_spades.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      {/* 10 */}
      <Image
        src="/img/10_of_clubs.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/10_of_diamonds.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/10_of_hearts.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/10_of_spades.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      {/* 11 */}
      <Image
        src="/img/11_of_clubs.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/11_of_diamonds.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/11_of_hearts.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/11_of_spades.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      {/* 12 */}
      <Image
        src="/img/12_of_clubs.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/12_of_diamonds.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/12_of_hearts.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/12_of_spades.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      {/* 13 */}
      <Image
        src="/img/13_of_clubs.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/13_of_diamonds.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/13_of_hearts.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
      <Image
        src="/img/13_of_spades.png"
        alt=""
        layout="respomsive"
        width={409}
        height={600}
      />
    </TrumpContainer>
  );
}

const TrumpContainer = styled.div`
  display: flex;
  flex-wrap: wrap;
`;
